### ISSUE TITLE
Dead link to O'Reilly

### ISSUE THREAD

**Issue by benkasminbullock** [dnmfarrell/Perl-Icons#4]
This link is dead too:

http://www.onlamp.com/pub/a/oreilly/perl/usage/

Apparently the page itself does not exist any more anywhere.

Edit: it is on archive.org from 2008;

https://web.archive.org/web/20080513235043/http://www.onlamp.com/pub/a/oreilly/perl/usage/

I looked at later years and it seems like it was already a dead link by around 2012 or so.

**Comment by dnmfarrell** [comment]
Thanks!
